<a href="https://colab.research.google.com/github/MazurovaNN/Parsing-API/blob/main/lesson8_dz8_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Импорт необходимых библиотек
import pandas as pd
import numpy as np

In [ ]:
# Загрузка датасета "Титаник
df = pd.read_csv('train.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Проверка того, в каких столбцах отсутствуют значения
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Заполнение пропущенных значений медианным значением столбца
median_age = df['Age'].median()
df['Age'] = df['Age'].fillna(median_age)

In [ ]:
# Заполнение пропущенных значений в столбце "Embarked" наиболее распространенным портом
mode_embarked = df['Embarked'].mode()[0]
df['Embarked'] = df['Embarked'].fillna(mode_embarked)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# проверка на дубликаты (здесь их нет)
duplicates = df.duplicated()
duplicates

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [ ]:
# вывод дубликатов (здесь нет)
duplicates_df = df[duplicates]
duplicates_df

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [ ]:
# функция удаления дубликатов (если бы они здесь были бы их бы удалили)
df = df.drop_duplicates()

In [ ]:
# Исправление неправильных значений в колонке "Sex"
df['Sex'] = df['Sex'].replace('male', 'M')
df['Sex'] = df['Sex'].replace('female', 'F')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Исправление отрицательных значений в колонке "Fare"
df.loc[df['Fare'] < 0, 'Fare'] = 0

In [ ]:
# Устранение несоответствий в колонке "Embarked"
df['Embarked'] = df['Embarked'].replace('S', 'Southampton')
df['Embarked'] = df['Embarked'].replace('C', 'Cherbourg')
df['Embarked'] = df['Embarked'].replace('Q', 'Queenstown')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,Southampton
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,Cherbourg
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,Southampton
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,Southampton
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,Southampton

In [ ]:
# Сопоставление противоречивых значений в столбце "Embarked"
port_map = {'Southampton' : 'S', 'Cherbourg' : 'C', 'Queenstown' : 'Q'}
df['Embarked'] = df['Embarked'].map(port_map)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",M,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",F,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",F,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",F,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",M,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Выполнение one-hot encoding столбца "Sex"
df = pd.get_dummies(df, columns=['Sex'])

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_F,Sex_M
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0,1

In [ ]:
# Выполнение label encoding столбца "Embarked"
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Embarked'] = le.fit_transform(df['Embarked'].astype(str))

In [ ]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_F,Sex_M
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,2,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,2,1,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,2,1,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,2,0,1
5,6,0,3,"Moran, Mr. James",28.0,0,0,330877,8.4583,NaN,1,0,1
6,7,0,1,"McCarthy, Mr. Timothy J",54.0,0,0,17463,51.8625,E46,2,0,1
7,8,0,3,"Palsson, Master. Gosta Leonard",2.0,3,1,349909,21.0750,NaN,2,0,1
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",27.0,0,2,347742,11.1333,NaN,2,1,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",14.0,1,0,237736,30.0708,NaN,0,1,0

In [ ]:
# Вычисление Z-score для столбца "Fare"
from scipy import stats

z = np.abs(stats.zscore(df['Fare']))

# Установка порогового значения Z-score
threshold = 3

# Выявление выбросов на основе Z-score
outliers = df['Fare'][z > threshold]

In [ ]:
df['Fare'].mean()

32.204207968574636

In [ ]:
outliers

27     263.0000
88     263.0000
118    247.5208
258    512.3292
299    247.5208
311    262.3750
341    263.0000
377    211.5000
380    227.5250
438    263.0000
527    221.7792
557    227.5250
679    512.3292
689    211.3375
700    227.5250
716    227.5250
730    211.3375
737    512.3292
742    262.3750
779    211.3375
Name: Fare, dtype: float64

In [ ]:
# Замена выбрасов медианным значением
df.loc[z > threshold, 'Fare'] = df['Fare'].median()

In [ ]:
df['Fare'].mean()

26.25910482603816

In [ ]:
# Например как выглядит замена 100 на единообразное значение 18
# 2 4 6 8 10 12 14 16 18 100
# 2 4 6 8 10 12 14 16 18 18

In [ ]:
# Винсоризация столбца "Fare"
from scipy.stats.mstats import winsorize

df['Fare'] = winsorize(df['Fare'], limits=[0.05, 0.05])

In [ ]:
df['Fare'].mean()

24.696483389450055

In [ ]:
# Трансформация столбца "Fare" с помощью логарифмической функции
df['Fare'] = np.log1p(df['Fare'])

In [ ]:
df['Fare'].mean()

2.9203914579094272

In [ ]:
prices = [10, 20, 30, 40, 50, 1000]

log_prices = np.log1p(prices)
log_prices

array([2.39789527, 3.04452244, 3.4339872 , 3.71357207, 3.93182563,
       6.90875478])

In [ ]:
from sklearn.preprocessing import StandardScaler

data = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(data.mean())
print(data.std())
# Создание объекта StandardScaler
scaler = StandardScaler()

# Подгонка и преобразование данных
scaled_data = scaler.fit_transform(data)

print(scaled_data)
print(scaled_data.mean())
print(scaled_data.std())

4.5
2.29128784747792
[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
0.0
1.0

In [ ]:
np.array(data).mean()

4.5

In [ ]:
type(scaled_data)

numpy.ndarray

In [ ]:
sales = pd.read_csv('sales.csv')
inventory = pd.read_csv('inventory.csv')

In [ ]:
sales

   product_id  sales_date  sales_quantity
0           1  2022-01-01              10
1           2  2022-01-01              20
2           1  2022-01-02              15
3           2  2022-01-02              25

In [ ]:
inventory

   product_id  sales_date  inventiry_level
0           1  2022-01-01              100
1           2  2022-01-01              200
2           1  2022-01-02               90
3           2  2022-01-02              180

In [ ]:
merged_data = pd.merge(sales, inventory, on=['product_id', 'sales_date'], how='left')

In [ ]:
merged_data

   product_id  sales_date  sales_quantity  inventiry_level
0           1  2022-01-01              10              100
1           2  2022-01-01              20              200
2           1  2022-01-02              15               90
3           2  2022-01-02              25              180

In [49]:
sales2 = pd.read_csv('sales2.csv')
sales2

   product_id region month  sales_quantity
0           1  North   Jan              10
1           2  North   Jan              20
2           1  South   Jan              15
3           2  South   Jan              25
4           1  North   Feb              12
5           2  North   Feb              22
6           1  South   Feb              18
7           2  South   Feb              28

In [52]:
pivot_data = sales2.pivot_table(index='product_id', columns=['region', 'month'], values='sales_quantity', aggfunc='sum')

In [53]:
pivot_data

region     North     South
month        Feb Jan   Feb Jan
product_id
1             12  10    18  15
2             22  20    28  25